// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID         pgtype.UUID
	Month      int32
	Year       int32
	CategoryID pgtype.UUID
	Amount     pgtype.Numeric
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
}

type Category struct {
	ID            pgtype.UUID
	CategoryName  string
	CreatedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
	Active        bool
	InactivatedAt pgtype.Timestamptz
	InactivatedBy pgtype.UUID
}

type Installment struct {
	ID                         pgtype.UUID
	Description                string
	Amount                     pgtype.Numeric
	TotalNumberInstallments    int32
	TotalRemainingInstallments int32
	NextDueDate                pgtype.Date
	CategoryID                 pgtype.UUID
	CreatedAt                  pgtype.Timestamptz
	CreatedBy                  pgtype.UUID
	UpdatedAt                  pgtype.Timestamptz
	UpdatedBy                  pgtype.UUID
}

type MonthlyRecurrency struct {
	ID            pgtype.UUID
	Description   string
	Amount        pgtype.Numeric
	NextDueDate   pgtype.Date
	CategoryID    pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
	Active        bool
	InactivatedAt pgtype.Timestamptz
	InactivatedBy pgtype.UUID
}

type PatternRule struct {
	ID            pgtype.UUID
	Pattern       string
	CategoryID    pgtype.UUID
	Hits          int32
	Misses        int32
	CreatedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
	Active        bool
	InactivatedAt pgtype.Timestamptz
	InactivatedBy pgtype.UUID
}

type PaymentMethod struct {
	ID                pgtype.UUID
	PaymentMethodName string
	UserPaymentMethod pgtype.UUID
	OwnerUserID       pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	Active            bool
	InactivatedAt     pgtype.Timestamptz
	InactivatedBy     pgtype.UUID
}

type Transaction struct {
	ID                pgtype.UUID
	Description       string
	Amount            pgtype.Numeric
	UserPaymentMethod pgtype.UUID
	CategoryID        pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	Active            bool
	InactivatedAt     pgtype.Timestamptz
	InactivatedBy     pgtype.UUID
}

type User struct {
	ID                         pgtype.UUID
	Username                   string
	Email                      string
	PassHash                   string
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	LastLoginAt                pgtype.Timestamptz
	PassExpirationDate         pgtype.Timestamptz
	Active                     bool
	InactivatedAt              pgtype.Timestamptz
	EmailVerified              bool
	VerificationToken          pgtype.Text
	VerificationTokenExpiresAt pgtype.Timestamptz
	PassResetToken             pgtype.Text
	PassResetTokenExpiresAt    pgtype.Timestamptz
}
