// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID         uuid.UUID
	Month      int32
	Year       int32
	CategoryID uuid.UUID
	Amount     pgtype.Numeric
	CreatedAt  pgtype.Timestamptz
	CreatedBy  uuid.UUID
	UpdatedAt  pgtype.Timestamptz
	UpdatedBy  pgtype.UUID
}

type Category struct {
	ID            uuid.UUID
	CategoryName  string
	CreatedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
	Active        bool
	InactivatedAt pgtype.Timestamptz
	InactivatedBy pgtype.UUID
}

type Installment struct {
	ID                         uuid.UUID
	Description                string
	Amount                     pgtype.Numeric
	TotalNumberInstallments    int32
	TotalRemainingInstallments int32
	NextDueDate                pgtype.Date
	CategoryID                 pgtype.UUID
	CreatedAt                  pgtype.Timestamptz
	CreatedBy                  uuid.UUID
	UpdatedAt                  pgtype.Timestamptz
	UpdatedBy                  pgtype.UUID
}

type MonthlyRecurrency struct {
	ID            uuid.UUID
	Description   string
	Amount        pgtype.Numeric
	NextDueDate   pgtype.Date
	CategoryID    pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	CreatedBy     uuid.UUID
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
	Active        bool
	InactivatedAt pgtype.Timestamptz
	InactivatedBy pgtype.UUID
}

type PasswordResetToken struct {
	ID        uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	Used      bool
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UserID    uuid.UUID
}

type PatternRule struct {
	ID            uuid.UUID
	Pattern       string
	CategoryID    pgtype.UUID
	Hits          int32
	Misses        int32
	CreatedAt     pgtype.Timestamptz
	CreatedBy     uuid.UUID
	UpdatedAt     pgtype.Timestamptz
	UpdatedBy     pgtype.UUID
	Active        bool
	InactivatedAt pgtype.Timestamptz
	InactivatedBy pgtype.UUID
}

type PaymentMethod struct {
	ID                uuid.UUID
	PaymentMethodName string
	UserPaymentMethod uuid.UUID
	OwnerUserID       uuid.UUID
	CreatedAt         pgtype.Timestamptz
	CreatedBy         uuid.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	Active            bool
	InactivatedAt     pgtype.Timestamptz
	InactivatedBy     pgtype.UUID
}

type Transaction struct {
	ID                uuid.UUID
	Description       string
	Amount            pgtype.Numeric
	UserPaymentMethod uuid.UUID
	CategoryID        pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	CreatedBy         uuid.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
	Active            bool
	InactivatedAt     pgtype.Timestamptz
	InactivatedBy     pgtype.UUID
}

type User struct {
	ID                 uuid.UUID
	Username           string
	Email              string
	PassHash           string
	PassExpirationDate pgtype.Timestamptz
	EmailVerified      bool
	Active             bool
	InactivatedAt      pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastLoginAt        pgtype.Timestamptz
}

type VerificationToken struct {
	ID        uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	Used      bool
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UserID    uuid.UUID
}
