// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verification_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (
    id,
    user_id,
    token,
    expires_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, token, expires_at, used, used_at, created_at, user_id
`

type CreateVerificationTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT id, token, expires_at, used, used_at, created_at, user_id
FROM verification_tokens
WHERE token = $1
`

func (q *Queries) GetVerificationToken(ctx context.Context, token string) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, token)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const markVerificationTokenUsed = `-- name: MarkVerificationTokenUsed :one
UPDATE verification_tokens
SET used = TRUE,
    used_at = NOW()
WHERE token = $1
RETURNING id, token, expires_at, used, used_at, created_at, user_id
`

func (q *Queries) MarkVerificationTokenUsed(ctx context.Context, token string) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, markVerificationTokenUsed, token)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.UsedAt,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}
